AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation template for S3 bucket resources needed for HUJI final project.

Parameters:
  PairName:
    Description: The name of the pair working on the project.
    Type: String
  CodePackageDate:
    Description: The date of the code package in ms.
    Type: String

Resources:
  PitkiotCodeBaseS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub huji-lightricks-pitkiot-code-${PairName}-bucket
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  PitkiotCodeBaseS3BucketName:
    Description: Name of code base bucket
    Value: !Ref PitkiotCodeBaseS3Bucket
    Export:
      Name: !Sub huji-lightricks-pitkiot-code-${PairName}-bucket-name

  PitkiotCodeBaseS3BucketArn:
    Description: ARN of code base bucket
    Value: !GetAtt PitkiotCodeBaseS3Bucket.Arn
    Export:
      Name: !Sub huji-lightricks-pitkiot-code-${PairName}-bucket-arn
